from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

IDENTITY_STATUSES = ("pending", "verified", "rejected", "expired", "additional_evidence_required")

# Government-issued documents that prove who someone is.
IDENTITY_DOCUMENT_TYPES = (
    "aadhaar",
    "pan_card",
    "passport",
    "driving_license",
    "voter_id",
    "national_id",
    "residence_permit",
    "permanent_resident_card",
    "government_photo_id",
    "government_employee_id",
)

# Utility bills, statements and similar documents that prove where someone lives --
# not identity documents, even though bills like these are commonly (and
# incorrectly) treated as ID. Kept in their own category deliberately.
ADDRESS_DOCUMENT_TYPES = (
    "electricity_bill",
    "water_bill",
    "gas_bill",
    "telephone_bill",
    "internet_bill",
    "property_tax_bill",
    "bank_statement",
    "credit_card_statement",
    "government_address_certificate",
    "rental_agreement",
)

OTHER_DOCUMENT_TYPES = (
    "birth_certificate",
    "marriage_certificate",
    "other_government_document",
    "other",
)

DOCUMENT_CATEGORIES = ("identity", "address", "other")

DOCUMENT_CATEGORY_BY_TYPE: dict[str, str] = {
    **{t: "identity" for t in IDENTITY_DOCUMENT_TYPES},
    **{t: "address" for t in ADDRESS_DOCUMENT_TYPES},
    **{t: "other" for t in OTHER_DOCUMENT_TYPES},
}

DOCUMENT_TYPES = IDENTITY_DOCUMENT_TYPES + ADDRESS_DOCUMENT_TYPES + OTHER_DOCUMENT_TYPES


class IdentityVerification(Base):
    __tablename__ = "identity_verifications"

    id: Mapped[int] = mapped_column(primary_key=True)
    party_id: Mapped[int] = mapped_column(ForeignKey("parties.id", ondelete="CASCADE"), nullable=False)
    document_type: Mapped[str] = mapped_column(String(50), nullable=False)
    document_category: Mapped[str] = mapped_column(String(20), default="identity")
    # User-supplied name for document_type == "other", e.g. "Company ID badge".
    custom_document_name: Mapped[str] = mapped_column(String(255), default="")
    # Optional free-text document number/reference (e.g. a passport number). Despite
    # the column name this was never actually encrypted -- kept for schema
    # continuity with the admin-facing read/write API, which still uses this name.
    encrypted_reference: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    evidence_ref: Mapped[str] = mapped_column(String(1024), default="")

    # The uploaded document itself. `document_file_path` is a filename generated by
    # save_identity_document(), resolved against settings.identity_upload_dir -- a
    # directory that is never mounted as a static route. Never expose this path
    # directly in an API response; documents are only readable through the
    # authenticated /document download routes.
    document_file_path: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    document_file_original_name: Mapped[str] = mapped_column(String(255), default="")
    document_file_content_type: Mapped[str] = mapped_column(String(100), default="")
    document_file_size: Mapped[int | None] = mapped_column(Integer, nullable=True)

    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # ZR-ENG-CLR-012 AC-31: idempotency marker for
    # services/verification_followups.py's expiry-reminder sweep -- same
    # pattern as OccupancyEligibilityCheck.follow_up_notified_at.
    expiry_notified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    verifier_admin_id: Mapped[int | None] = mapped_column(ForeignKey("admin_users.id"), nullable=True)
    verifier_notes: Mapped[str] = mapped_column(String(2000), default="")
    status: Mapped[str] = mapped_column(String(20), default="pending")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    party: Mapped["Party"] = relationship(back_populates="identity_verifications")
    verifier_admin: Mapped["AdminUser"] = relationship()

    @property
    def has_document(self) -> bool:
        return bool(self.document_file_path)
