from datetime import datetime, timezone

from sqlalchemy import JSON, Boolean, DateTime, Float, ForeignKey, Integer, String, event
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

IDENTITY_STATUSES = ("pending", "verified", "rejected", "expired", "additional_evidence_required")

# Government-issued documents that prove who someone is.
IDENTITY_DOCUMENT_TYPES = (
    "aadhaar",
    "pan_card",
    "passport",
    "driving_license",
    "voter_id",
    "national_id",
    "residence_permit",
    "permanent_resident_card",
    "government_photo_id",
    "government_employee_id",
)

# Utility bills, statements and similar documents that prove where someone lives --
# not identity documents, even though bills like these are commonly (and
# incorrectly) treated as ID. Kept in their own category deliberately.
ADDRESS_DOCUMENT_TYPES = (
    "electricity_bill",
    "water_bill",
    "gas_bill",
    "telephone_bill",
    "internet_bill",
    "property_tax_bill",
    "bank_statement",
    "credit_card_statement",
    "government_address_certificate",
    "rental_agreement",
)

OTHER_DOCUMENT_TYPES = (
    "birth_certificate",
    "marriage_certificate",
    "other_government_document",
    "other",
)

DOCUMENT_CATEGORIES = ("identity", "address", "other")

DOCUMENT_CATEGORY_BY_TYPE: dict[str, str] = {
    **{t: "identity" for t in IDENTITY_DOCUMENT_TYPES},
    **{t: "address" for t in ADDRESS_DOCUMENT_TYPES},
    **{t: "other" for t in OTHER_DOCUMENT_TYPES},
}

DOCUMENT_TYPES = IDENTITY_DOCUMENT_TYPES + ADDRESS_DOCUMENT_TYPES + OTHER_DOCUMENT_TYPES


class IdentityVerification(Base):
    """One attempt to prove the person's identity (ZR-IDENTITY-001): the
    verification session and its evidence. The account-level outcome lives on
    models/identity_profile.py:IdentityProfile, which every gate reads.

    `status` is the legacy vocabulary (pending / verified / rejected / ...)
    kept in step with `session_state` so older readers keep working;
    `session_state` is the canonical Section 7.1 state."""

    __tablename__ = "identity_verifications"

    id: Mapped[int] = mapped_column(primary_key=True)
    party_id: Mapped[int] = mapped_column(ForeignKey("parties.id", ondelete="CASCADE"), nullable=False)
    # Blank until the document is captured (a session starts before that).
    document_type: Mapped[str] = mapped_column(String(50), nullable=False, default="")
    document_category: Mapped[str] = mapped_column(String(20), default="identity")
    # User-supplied name for document_type == "other", e.g. "Company ID badge".
    custom_document_name: Mapped[str] = mapped_column(String(255), default="")
    # The typed document number, Fernet-encrypted at rest
    # (core/field_encryption.py:encrypt_text). Never returned by any API --
    # only masked_document_number is (Section 5.4 / 9.2).
    encrypted_reference: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    masked_document_number: Mapped[str] = mapped_column(String(32), default="")
    # SHA-256 of the normalized number, to spot the same document across
    # accounts without decrypting anything.
    document_number_hash: Mapped[str] = mapped_column(String(64), default="", index=True)
    evidence_ref: Mapped[str] = mapped_column(String(1024), default="")

    # The uploaded document itself. `document_file_path` is a filename generated by
    # save_identity_document(), resolved against settings.identity_upload_dir -- a
    # directory that is never mounted as a static route. Never expose this path
    # directly in an API response; documents are only readable through the
    # authenticated /document download routes.
    document_file_path: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    document_file_original_name: Mapped[str] = mapped_column(String(255), default="")
    document_file_content_type: Mapped[str] = mapped_column(String(100), default="")
    document_file_size: Mapped[int | None] = mapped_column(Integer, nullable=True)

    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # ZR-ENG-CLR-012 AC-31: idempotency marker for
    # services/verification_followups.py's expiry-reminder sweep -- same
    # pattern as OccupancyEligibilityCheck.follow_up_notified_at.
    expiry_notified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    verifier_admin_id: Mapped[int | None] = mapped_column(ForeignKey("admin_users.id"), nullable=True)
    verifier_notes: Mapped[str] = mapped_column(String(2000), default="")
    status: Mapped[str] = mapped_column(String(40), default="pending")

    # -- ZR-IDENTITY-001 session fields --
    session_state: Mapped[str] = mapped_column(String(30), default="IN_PROGRESS", nullable=False)
    method_type: Mapped[str] = mapped_column(String(30), default="DOCUMENT")
    country_code: Mapped[str] = mapped_column(String(10), default="")
    # Routing hint only (OWNER / AGENT / SUBLETTER) -- never an identity attribute.
    role_context: Mapped[str] = mapped_column(String(20), default="")
    assurance_level: Mapped[str] = mapped_column(String(10), default="IV-0")
    provider_code: Mapped[str] = mapped_column(String(50), default="")
    provider_session_id: Mapped[str] = mapped_column(String(200), default="")
    normalized_outcome: Mapped[str] = mapped_column(String(20), default="")
    reason_codes: Mapped[list] = mapped_column(JSON, default=list)
    # Section 8.2 match_results, normalized (no vendor scores).
    match_results: Mapped[dict] = mapped_column(JSON, default=dict)
    # Legal name the person confirmed for this attempt (Section 5.2).
    legal_name_snapshot: Mapped[str] = mapped_column(String(600), default="")
    # Why an alternative/manual route was asked for (Section 8.3).
    alternative_reason: Mapped[str] = mapped_column(String(60), default="")
    idempotency_key: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    attested_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    submitted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    decided_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    escalated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # Section 5.3 "Continue on phone": a short-lived, single-use token (only
    # its SHA-256 is stored; no identity data in it). The phone must still be
    # signed in to the same account to claim it.
    handoff_token_hash: Mapped[str] = mapped_column(String(64), default="")
    # Section 9.2: raw evidence is deleted once the country pack's retention
    # period after the decision has passed; the decision, masked number and
    # hashes stay (services/identity/service.py:purge_expired_evidence).
    evidence_purged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # ZR-IDV-ADR-001 Section 11 -- hosted provider (Veriff) session.
    # The launch URL is Fernet-encrypted (it lets someone continue the
    # capture) and never logged; sessionToken is deliberately not stored.
    provider_session_url_encrypted: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    provider_attempt_id: Mapped[str] = mapped_column(String(200), default="")
    # The provider's own outcome, as a constrained value (approved / review /
    # resubmission_requested / declined / expired / abandoned).
    provider_decision: Mapped[str] = mapped_column(String(40), default="")
    # Which privacy / biometric notice the person accepted (pack country + version).
    consent_notice_version: Mapped[str] = mapped_column(String(40), default="")
    handoff_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # services/document_ocr.py: the document number Tesseract actually read off
    # the uploaded image, and its average OCR confidence (0-100) -- distinct
    # from encrypted_reference above, which is whatever the user typed into the
    # form and was never cross-checked against the image. Null whenever OCR
    # didn't run (Tesseract not installed) or found no confident match.
    ocr_extracted_number: Mapped[str | None] = mapped_column(String(64), nullable=True)
    ocr_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    # services/document_ocr.py:check_name_in_document -- whether the
    # submitting user's OWN registered account name (UserAccount.full_name)
    # was found in this document's OCR text. Not a name EXTRACTED from the
    # document (unstructured OCR text has no reliable "this is the name
    # field" signal without real document-layout parsing, which this build
    # doesn't have) -- a cross-match of a KNOWN claimed name against the
    # document, same shape every real proof-of-address/KYC vendor uses.
    # Null whenever OCR didn't run.
    ocr_name_matched: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    # services/document_ocr.py:extract_name_from_mrz -- a REAL name parsed
    # off a passport's own machine-readable zone (ICAO 9303, a genuinely
    # standardized, reliably parseable format -- not a heuristic guess).
    # Only ever populated for passports whose MRZ line read cleanly; null
    # for every other document type or a passport where it didn't parse.
    # Property verification (crud/property_verification.py) prefers this
    # over the account's typed full_name when checking for a name match,
    # since this came from the real document itself.
    extracted_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    party: Mapped["Party"] = relationship(back_populates="identity_verifications")
    verifier_admin: Mapped["AdminUser"] = relationship()

    @property
    def has_document(self) -> bool:
        return bool(self.document_file_path)

    @property
    def auto_flagged(self) -> bool:
        """True when the automated OCR scan (not a human admin) sent this
        submission back for more evidence -- crud/identity_verification.py's
        _reroute_to_additional_evidence never sets verifier_admin_id, while an
        admin's request_additional_evidence always does. A super admin can
        still overrule it (approve/reject) from the review queue."""
        return self.status == "additional_evidence_required" and self.verifier_admin_id is None


# Rows written with only the legacy `status` (older code paths, fixtures)
# get the matching canonical session_state, so the two never disagree.
_STATE_FOR_LEGACY_STATUS = {
    "pending": "PENDING_REVIEW", "verified": "VERIFIED", "rejected": "FAILED",
    "additional_evidence_required": "ACTION_REQUIRED", "expired": "REVERIFICATION_REQUIRED",
}


@event.listens_for(IdentityVerification, "before_insert")
def _derive_session_state(_mapper, _connection, target: IdentityVerification) -> None:
    if target.session_state in (None, "IN_PROGRESS") and target.status in _STATE_FOR_LEGACY_STATUS:
        target.session_state = _STATE_FOR_LEGACY_STATUS[target.status]
