"""ZR-IDENTITY-001: identity profiles, country packs, provider events, session fields

Revision ID: 0341b3322b25
Revises: c7e1f4a2b9d6
Create Date: 2026-10-01 15:51:18.215549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0341b3322b25'
down_revision: Union[str, None] = 'c7e1f4a2b9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_regulatory_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('accepted_document_types', sa.JSON(), nullable=False),
    sa.Column('available_methods', sa.JSON(), nullable=False),
    sa.Column('date_of_birth_required', sa.Boolean(), nullable=False),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('biometric_consent_text', sa.Text(), nullable=False),
    sa.Column('privacy_notice_text', sa.Text(), nullable=False),
    sa.Column('evidence_retention_days', sa.Integer(), nullable=True),
    sa.Column('reverification_interval_days', sa.Integer(), nullable=True),
    sa.Column('reverify_on_account_recovery', sa.Boolean(), nullable=False),
    sa.Column('document_provider_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'version', name='uq_identity_pack_country_version')
    )
    op.create_index(op.f('ix_identity_regulatory_packs_country_code'), 'identity_regulatory_packs', ['country_code'], unique=False)
    op.create_table('identity_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('assurance_level', sa.String(length=10), nullable=False),
    sa.Column('given_name', sa.String(length=200), nullable=False),
    sa.Column('middle_names', sa.String(length=200), nullable=False),
    sa.Column('family_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('verified_legal_name', sa.String(length=600), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverification_required_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverification_reason', sa.String(length=60), nullable=False),
    sa.Column('verification_method', sa.String(length=30), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('provider_subject_reference', sa.String(length=255), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('current_verification_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_profiles_party_id'), 'identity_profiles', ['party_id'], unique=True)
    op.create_table('identity_provider_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.Column('identity_verification_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_verification_id'], ['identity_verifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'provider_event_id', name='uq_identity_provider_event')
    )
    op.create_foreign_key(
        'fk_identity_profiles_current_verification_id', 'identity_profiles', 'identity_verifications',
        ['current_verification_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('identity_verifications', sa.Column('masked_document_number', sa.String(length=32), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('document_number_hash', sa.String(length=64), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('session_state', sa.String(length=30), nullable=False, server_default=sa.text("'IN_PROGRESS'")))
    op.add_column('identity_verifications', sa.Column('method_type', sa.String(length=30), nullable=False, server_default=sa.text("'DOCUMENT'")))
    op.add_column('identity_verifications', sa.Column('country_code', sa.String(length=10), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('role_context', sa.String(length=20), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('assurance_level', sa.String(length=10), nullable=False, server_default=sa.text("'IV-0'")))
    op.add_column('identity_verifications', sa.Column('provider_code', sa.String(length=50), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('provider_session_id', sa.String(length=200), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('normalized_outcome', sa.String(length=20), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('reason_codes', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('identity_verifications', sa.Column('match_results', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('identity_verifications', sa.Column('legal_name_snapshot', sa.String(length=600), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('alternative_reason', sa.String(length=60), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.add_column('identity_verifications', sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('identity_verifications', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('identity_verifications', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('identity_verifications', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('identity_verifications', sa.Column('handoff_token_hash', sa.String(length=64), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('handoff_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_identity_verifications_document_number_hash'), 'identity_verifications', ['document_number_hash'], unique=False)
    op.create_index(op.f('ix_identity_verifications_idempotency_key'), 'identity_verifications', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###

    # -- data: existing rows onto the new model ---------------------------
    # Imported here (not at module top) so the migration doesn't depend on
    # app code at import time.
    import hashlib
    import json

    from cryptography.fernet import Fernet, InvalidToken

    from app.core.config import settings

    fernet = Fernet(settings.field_encryption_key.encode("utf-8"))
    conn = op.get_bind()
    state_for = {
        "pending": "PENDING_REVIEW", "verified": "VERIFIED", "rejected": "FAILED",
        "additional_evidence_required": "ACTION_REQUIRED", "expired": "REVERIFICATION_REQUIRED",
    }

    def mask(value):
        cleaned = "".join(ch for ch in (value or "") if ch.isalnum())
        return f"\u2022\u2022\u2022\u2022{cleaned[-4:]}" if cleaned else ""

    rows = conn.execute(sa.text(
        "SELECT id, document_type, encrypted_reference, ocr_extracted_number, status, verified_at, created_at "
        "FROM identity_verifications"
    )).mappings().all()
    for row in rows:
        number = row["encrypted_reference"] or ""
        try:
            plain = fernet.decrypt(number.encode("utf-8")).decode("utf-8") if number else ""
            encrypted = number or None
        except InvalidToken:
            plain = number
            encrypted = fernet.encrypt(number.encode("utf-8")).decode("utf-8") if number else None
        cleaned = "".join(ch for ch in plain.upper() if ch.isalnum())
        conn.execute(sa.text(
            "UPDATE identity_verifications SET encrypted_reference = :enc, masked_document_number = :masked, "
            "document_number_hash = :hash, ocr_extracted_number = :ocr, session_state = :state, "
            "submitted_at = created_at, decided_at = CASE WHEN status IN ('verified', 'rejected') THEN updated_at END "
            "WHERE id = :id"
        ), {
            "enc": encrypted, "masked": mask(plain),
            "hash": hashlib.sha256(f"{row['document_type']}:{cleaned}".encode("utf-8")).hexdigest() if cleaned else "",
            "ocr": mask(row["ocr_extracted_number"]) or None,
            "state": state_for.get(row["status"], "PENDING_REVIEW"), "id": row["id"],
        })

    # One identity profile per party that has any verification: VERIFIED
    # when its latest verified record is still valid, otherwise the state of
    # its latest record.
    parties = conn.execute(sa.text("SELECT DISTINCT party_id FROM identity_verifications")).scalars().all()
    for party_id in parties:
        latest_verified = conn.execute(sa.text(
            "SELECT id, verified_at, document_type FROM identity_verifications "
            "WHERE party_id = :p AND status = 'verified' AND (expires_at IS NULL OR expires_at > now()) "
            "ORDER BY id DESC LIMIT 1"
        ), {"p": party_id}).mappings().first()
        latest = conn.execute(sa.text(
            "SELECT id, status FROM identity_verifications WHERE party_id = :p ORDER BY id DESC LIMIT 1"
        ), {"p": party_id}).mappings().first()
        user = conn.execute(sa.text(
            "SELECT full_name FROM user_accounts WHERE party_id = :p ORDER BY id LIMIT 1"
        ), {"p": party_id}).scalar() or ""
        parts = user.split()
        given = parts[0] if parts else ""
        family = parts[-1] if len(parts) > 1 else ""
        middle = " ".join(parts[1:-1]) if len(parts) > 2 else ""
        if latest_verified:
            state, current, verified_at = "VERIFIED", latest_verified["id"], latest_verified["verified_at"]
            # Identity no longer expires with the document (Section 7.2).
            conn.execute(sa.text("UPDATE identity_verifications SET expires_at = NULL WHERE id = :id"),
                         {"id": latest_verified["id"]})
            conn.execute(sa.text(
                "UPDATE verification_credentials SET expires_at = NULL "
                "WHERE source_identity_verification_id = :id AND status = 'VALID'"
            ), {"id": latest_verified["id"]})
        else:
            state, current, verified_at = state_for.get(latest["status"], "PENDING_REVIEW"), None, None
        conn.execute(sa.text(
            "INSERT INTO identity_profiles (party_id, state, assurance_level, given_name, middle_names, family_name, "
            "country_code, verified_legal_name, verified_at, reverification_reason, verification_method, "
            "provider_code, provider_subject_reference, reason_codes, current_verification_id, version, "
            "created_at, updated_at) VALUES (:p, :state, :level, :given, :middle, :family, '', :vname, :vat, '', "
            ":method, 'legacy', '', :codes, :current, 1, now(), now())"
        ), {
            "p": party_id, "state": state, "level": "IV-1" if latest_verified else "IV-0",
            "given": given, "middle": middle, "family": family,
            "vname": user if latest_verified else "", "vat": verified_at,
            "method": "DOCUMENT" if latest_verified else "", "codes": json.dumps([]), "current": current,
        })


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_identity_profiles_current_verification_id', 'identity_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_identity_verifications_idempotency_key'), table_name='identity_verifications')
    op.drop_index(op.f('ix_identity_verifications_document_number_hash'), table_name='identity_verifications')
    op.drop_column('identity_verifications', 'handoff_expires_at')
    op.drop_column('identity_verifications', 'handoff_token_hash')
    op.drop_column('identity_verifications', 'escalated_at')
    op.drop_column('identity_verifications', 'decided_at')
    op.drop_column('identity_verifications', 'submitted_at')
    op.drop_column('identity_verifications', 'attested_at')
    op.drop_column('identity_verifications', 'idempotency_key')
    op.drop_column('identity_verifications', 'alternative_reason')
    op.drop_column('identity_verifications', 'legal_name_snapshot')
    op.drop_column('identity_verifications', 'match_results')
    op.drop_column('identity_verifications', 'reason_codes')
    op.drop_column('identity_verifications', 'normalized_outcome')
    op.drop_column('identity_verifications', 'provider_session_id')
    op.drop_column('identity_verifications', 'provider_code')
    op.drop_column('identity_verifications', 'assurance_level')
    op.drop_column('identity_verifications', 'role_context')
    op.drop_column('identity_verifications', 'country_code')
    op.drop_column('identity_verifications', 'method_type')
    op.drop_column('identity_verifications', 'session_state')
    op.drop_column('identity_verifications', 'document_number_hash')
    op.drop_column('identity_verifications', 'masked_document_number')
    op.drop_table('identity_provider_events')
    op.drop_index(op.f('ix_identity_profiles_party_id'), table_name='identity_profiles')
    op.drop_table('identity_profiles')
    op.drop_index(op.f('ix_identity_regulatory_packs_country_code'), table_name='identity_regulatory_packs')
    op.drop_table('identity_regulatory_packs')
    # ### end Alembic commands ###
