"""add missing fk indexes for finance and occupancy

Revision ID: 4ce282ecddbb
Revises: d2a1ff9b9fc4
Create Date: 2026-09-07 12:40:05.314703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce282ecddbb'
down_revision: Union[str, None] = 'd2a1ff9b9fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_listings_room_id'), 'listings', ['room_id'], unique=False)
    op.create_index(op.f('ix_obligations_agreement_id'), 'obligations', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_obligations_occupancy_id'), 'obligations', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_occupancies_listing_id'), 'occupancies', ['listing_id'], unique=False)
    op.create_index(op.f('ix_occupancies_room_id'), 'occupancies', ['room_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_obligation_id'), 'payment_allocations', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_obligation_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_occupancies_room_id'), table_name='occupancies')
    op.drop_index(op.f('ix_occupancies_listing_id'), table_name='occupancies')
    op.drop_index(op.f('ix_obligations_occupancy_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_agreement_id'), table_name='obligations')
    op.drop_index(op.f('ix_listings_room_id'), table_name='listings')
    # ### end Alembic commands ###
