"""ZR-IDV-ADR-001: provider reason-code mappings, go-live gates, connection checks

Revision ID: 4d26afb5d759
Revises: d3e7d3fbfb7a
Create Date: 2026-10-01 17:29:19.984352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d26afb5d759'
down_revision: Union[str, None] = 'd3e7d3fbfb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_provider_reason_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('provider_decision', sa.String(length=40), nullable=False),
    sa.Column('provider_reason_code', sa.String(length=40), nullable=False),
    sa.Column('zoiko_reason_code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'provider_decision', 'provider_reason_code', name='uq_identity_reason_mapping')
    )
    op.create_table('identity_go_live_gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('gate_code', sa.String(length=40), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'gate_code', name='uq_identity_go_live_gate')
    )
    op.create_table('identity_provider_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('integration_id', sa.String(length=50), nullable=False),
    sa.Column('check_type', sa.String(length=40), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=False),
    sa.Column('run_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_provider_checks')
    op.drop_table('identity_go_live_gates')
    op.drop_table('identity_provider_reason_mappings')
    # ### end Alembic commands ###
