"""direct sublet payments, remove rent card rail

Revision ID: 542ea00324ed
Revises: ea318f7cf1bc
Create Date: 2026-10-05 14:13:50.316970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '542ea00324ed'
down_revision: Union[str, None] = 'ea318f7cf1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sublet_payment_arrangements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sublet_request_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rent_payee_type', sa.String(length=20), nullable=False),
    sa.Column('rent_payee_party_id', sa.Integer(), nullable=True),
    sa.Column('rent_payee_basis', sa.String(length=60), nullable=False),
    sa.Column('payee_authority_ref', sa.String(length=80), nullable=False),
    sa.Column('deposit_route', sa.String(length=30), nullable=False),
    sa.Column('deposit_payee_party_id', sa.Integer(), nullable=True),
    sa.Column('custodian_name', sa.String(length=200), nullable=False),
    sa.Column('custodian_reference', sa.String(length=200), nullable=False),
    sa.Column('custodian_instructions', sa.String(length=2000), nullable=False),
    sa.Column('accepted_methods', sa.JSON(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rent_due_day', sa.Integer(), nullable=True),
    sa.Column('first_payment_date', sa.Date(), nullable=True),
    sa.Column('deposit_pack_version', sa.String(length=20), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amendment_reason', sa.String(length=1000), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['deposit_payee_party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['sublet_payment_arrangements.id'], ),
    sa.ForeignKeyConstraint(['rent_payee_party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['sublet_request_id'], ['sublet_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sublet_payment_arrangements_status'), 'sublet_payment_arrangements', ['status'], unique=False)
    op.create_index(op.f('ix_sublet_payment_arrangements_sublet_request_id'), 'sublet_payment_arrangements', ['sublet_request_id'], unique=False)
    # Rent is paid directly (bank / UPI / cash): no card session state remains.
    op.execute("UPDATE rental_payment_obligations SET status = 'DUE' WHERE status IN ('PAYMENT_SESSION_STARTED', 'PROVIDER_PROCESSING')")
    op.drop_index(op.f('ix_rental_payment_provider_accounts_party_id'), table_name='rental_payment_provider_accounts')
    op.drop_index(op.f('uq_rental_payment_provider_accounts_active_party'), table_name='rental_payment_provider_accounts', postgresql_where="((status)::text <> 'SUPERSEDED'::text)")
    op.drop_table('rental_payment_provider_accounts')
    op.drop_table('rental_payment_provider_events')
    op.drop_index(op.f('ix_external_payment_sessions_obligation_id'), table_name='external_payment_sessions')
    op.drop_table('external_payment_sessions')
    op.add_column('rental_payment_obligations', sa.Column('payee_type', sa.String(length=20), server_default='LANDLORD_AGENT', nullable=False))
    op.add_column('rental_payment_obligations', sa.Column('payee_basis', sa.String(length=60), server_default='', nullable=False))
    op.add_column('rental_payment_obligations', sa.Column('payee_authority_ref', sa.String(length=80), server_default='', nullable=False))
    op.add_column('rental_payment_obligations', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('rental_payment_obligations', sa.Column('period_end', sa.Date(), nullable=True))
    op.add_column('rental_payment_obligations', sa.Column('arrangement_id', sa.Integer(), nullable=True))
    op.add_column('rental_payment_obligations', sa.Column('arrangement_version', sa.Integer(), nullable=True))
    op.add_column('rental_payment_obligations', sa.Column('agreement_version_no', sa.Integer(), nullable=True))
    op.add_column('rental_payment_obligations', sa.Column('payment_reference', sa.String(length=40), server_default='', nullable=False))
    op.add_column('rental_payment_obligations', sa.Column('platform_fee_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('rental_payment_obligations', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_rental_payment_obligations_arrangement_id'), 'rental_payment_obligations', ['arrangement_id'], unique=False)
    op.create_foreign_key('fk_rpo_arrangement', 'rental_payment_obligations', 'sublet_payment_arrangements', ['arrangement_id'], ['id'], ondelete='SET NULL')
    op.drop_column('rental_payment_records', 'provider_dispute_status')
    op.drop_column('rental_payment_records', 'refunded_amount')
    op.drop_column('rental_payment_records', 'provider_refund_id')
    op.drop_column('rental_payment_records', 'provider_dispute_id')
    op.add_column('rental_payment_returns', sa.Column('obligation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rental_payment_returns_obligation_id'), 'rental_payment_returns', ['obligation_id'], unique=False)
    op.create_foreign_key('fk_rpr_obligation', 'rental_payment_returns', 'rental_payment_obligations', ['obligation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_rpr_obligation', 'rental_payment_returns', type_='foreignkey')
    op.drop_index(op.f('ix_rental_payment_returns_obligation_id'), table_name='rental_payment_returns')
    op.drop_column('rental_payment_returns', 'obligation_id')
    op.add_column('rental_payment_records', sa.Column('provider_dispute_id', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('rental_payment_records', sa.Column('provider_refund_id', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('rental_payment_records', sa.Column('refunded_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('rental_payment_records', sa.Column('provider_dispute_status', sa.VARCHAR(length=30), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('fk_rpo_arrangement', 'rental_payment_obligations', type_='foreignkey')
    op.drop_index(op.f('ix_rental_payment_obligations_arrangement_id'), table_name='rental_payment_obligations')
    op.drop_column('rental_payment_obligations', 'version')
    op.drop_column('rental_payment_obligations', 'platform_fee_amount')
    op.drop_column('rental_payment_obligations', 'payment_reference')
    op.drop_column('rental_payment_obligations', 'agreement_version_no')
    op.drop_column('rental_payment_obligations', 'arrangement_version')
    op.drop_column('rental_payment_obligations', 'arrangement_id')
    op.drop_column('rental_payment_obligations', 'period_end')
    op.drop_column('rental_payment_obligations', 'period_start')
    op.drop_column('rental_payment_obligations', 'payee_authority_ref')
    op.drop_column('rental_payment_obligations', 'payee_basis')
    op.drop_column('rental_payment_obligations', 'payee_type')
    op.create_table('rental_payment_provider_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_event_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('external_payment_session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['external_payment_session_id'], ['external_payment_sessions.id'], name=op.f('rental_payment_provider_events_external_payment_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rental_payment_provider_events_pkey')),
    sa.UniqueConstraint('provider_event_id', name=op.f('rental_payment_provider_events_provider_event_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('external_payment_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_guest_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('recipient_stripe_account_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider_checkout_session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider_payment_intent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('failure_message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['rental_payment_obligations.id'], name=op.f('external_payment_sessions_obligation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_guest_id'], ['guests.id'], name=op.f('external_payment_sessions_tenant_guest_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('external_payment_sessions_pkey')),
    sa.UniqueConstraint('provider_checkout_session_id', name=op.f('external_payment_sessions_provider_checkout_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_external_payment_sessions_obligation_id'), 'external_payment_sessions', ['obligation_id'], unique=False)
    op.create_table('rental_payment_provider_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stripe_account_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('details_submitted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('charges_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payouts_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('verification_code_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('verification_code_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verification_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_high_risk', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('high_risk_reason', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('rental_payment_provider_accounts_party_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rental_payment_provider_accounts_pkey')),
    sa.UniqueConstraint('stripe_account_id', name=op.f('rental_payment_provider_accounts_stripe_account_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('uq_rental_payment_provider_accounts_active_party'), 'rental_payment_provider_accounts', ['party_id'], unique=True, postgresql_where="((status)::text <> 'SUPERSEDED'::text)")
    op.create_index(op.f('ix_rental_payment_provider_accounts_party_id'), 'rental_payment_provider_accounts', ['party_id'], unique=False)
    op.drop_index(op.f('ix_sublet_payment_arrangements_sublet_request_id'), table_name='sublet_payment_arrangements')
    op.drop_index(op.f('ix_sublet_payment_arrangements_status'), table_name='sublet_payment_arrangements')
    op.drop_table('sublet_payment_arrangements')
    # ### end Alembic commands ###
