"""property verification duplicate answer and pin device

Revision ID: 833ffed87973
Revises: 542ea00324ed
Create Date: 2026-10-05 15:08:34.860922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833ffed87973'
down_revision: Union[str, None] = '542ea00324ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_location_verifications', sa.Column('duplicate_host_answer', sa.String(length=20), server_default='', nullable=False))
    op.add_column('property_location_verifications', sa.Column('duplicate_host_note', sa.String(length=500), server_default='', nullable=False))
    op.add_column('property_location_verifications', sa.Column('pin_adjust_device', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_location_verifications', 'pin_adjust_device')
    op.drop_column('property_location_verifications', 'duplicate_host_note')
    op.drop_column('property_location_verifications', 'duplicate_host_answer')
    # ### end Alembic commands ###
