"""property location verification ZR-PROPERTY-VERIFY-001

Revision ID: 8c720df07c87
Revises: 7c1e2f9a4b10
Create Date: 2026-10-05 11:11:21.406626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c720df07c87'
down_revision: Union[str, None] = '7c1e2f9a4b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_regulatory_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('required_address_fields', sa.JSON(), nullable=False),
    sa.Column('accepted_evidence_types', sa.JSON(), nullable=False),
    sa.Column('unit_required_for', sa.JSON(), nullable=False),
    sa.Column('pin_move_review_meters', sa.Integer(), nullable=False),
    sa.Column('public_location_decimals', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('expiring_soon_days', sa.Integer(), nullable=False),
    sa.Column('evidence_retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_regulatory_packs_country_code'), 'property_regulatory_packs', ['country_code'], unique=False)
    op.create_table('property_location_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('pack_version', sa.Integer(), nullable=True),
    sa.Column('entry_mode', sa.String(length=10), nullable=False),
    sa.Column('submitted_address', sa.JSON(), nullable=False),
    sa.Column('canonical_address', sa.JSON(), nullable=False),
    sa.Column('suggested_address', sa.JSON(), nullable=False),
    sa.Column('address_status', sa.String(length=12), nullable=False),
    sa.Column('address_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geocode_status', sa.String(length=12), nullable=False),
    sa.Column('location_precision', sa.String(length=14), nullable=False),
    sa.Column('original_latitude', sa.Float(), nullable=True),
    sa.Column('original_longitude', sa.Float(), nullable=True),
    sa.Column('confirmed_latitude', sa.Float(), nullable=True),
    sa.Column('confirmed_longitude', sa.Float(), nullable=True),
    sa.Column('pin_status', sa.String(length=16), nullable=False),
    sa.Column('pin_moved_meters', sa.Float(), nullable=True),
    sa.Column('pin_reverse_geocode', sa.String(length=500), nullable=False),
    sa.Column('pin_adjust_reason', sa.String(length=300), nullable=False),
    sa.Column('pin_adjust_count', sa.Integer(), nullable=False),
    sa.Column('property_kind', sa.String(length=12), nullable=False),
    sa.Column('building_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=False),
    sa.Column('address_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('duplicate_of_property_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_place_id', sa.String(length=300), nullable=False),
    sa.Column('provider_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('existence_status', sa.String(length=20), nullable=False),
    sa.Column('source_check', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_admin_id', sa.Integer(), nullable=True),
    sa.Column('first_approver_admin_id', sa.Integer(), nullable=True),
    sa.Column('review_reason_code', sa.String(length=40), nullable=False),
    sa.Column('review_note', sa.String(length=1000), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('submit_idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['first_approver_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'idempotency_key', name='uq_plv_party_idempotency')
    )
    op.create_index(op.f('ix_property_location_verifications_address_fingerprint'), 'property_location_verifications', ['address_fingerprint'], unique=False)
    op.create_index(op.f('ix_property_location_verifications_property_id'), 'property_location_verifications', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_location_verifications_state'), 'property_location_verifications', ['state'], unique=False)
    op.create_table('property_location_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('stored_filename', sa.String(length=300), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('readable', sa.Boolean(), nullable=False),
    sa.Column('address_matched', sa.Boolean(), nullable=True),
    sa.Column('unit_matched', sa.Boolean(), nullable=True),
    sa.Column('reused_elsewhere', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['property_location_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_location_evidence_sha256'), 'property_location_evidence', ['sha256'], unique=False)
    op.create_index(op.f('ix_property_location_evidence_verification_id'), 'property_location_evidence', ['verification_id'], unique=False)
    op.add_column('properties', sa.Column('address_line_1', sa.String(length=300), server_default='', nullable=False))
    op.add_column('properties', sa.Column('address_line_2', sa.String(length=300), server_default='', nullable=False))
    op.add_column('properties', sa.Column('subpremise', sa.String(length=50), server_default='', nullable=False))
    op.add_column('properties', sa.Column('locality', sa.String(length=200), server_default='', nullable=False))
    op.add_column('properties', sa.Column('administrative_area', sa.String(length=200), server_default='', nullable=False))
    op.add_column('properties', sa.Column('postal_code', sa.String(length=20), server_default='', nullable=False))
    op.add_column('properties', sa.Column('country_code', sa.String(length=2), server_default='', nullable=False))
    op.add_column('properties', sa.Column('canonical_formatted_address', sa.String(length=600), server_default='', nullable=False))
    op.add_column('properties', sa.Column('property_kind', sa.String(length=12), server_default='', nullable=False))
    op.add_column('properties', sa.Column('building_name', sa.String(length=200), server_default='', nullable=False))
    op.add_column('properties', sa.Column('floor', sa.String(length=20), server_default='', nullable=False))
    op.add_column('properties', sa.Column('latitude_private', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('longitude_private', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('location_precision', sa.String(length=14), server_default='', nullable=False))
    op.add_column('properties', sa.Column('public_location_decimals', sa.Integer(), server_default='2', nullable=False))
    op.add_column('properties', sa.Column('geocode_status', sa.String(length=12), server_default='', nullable=False))
    op.add_column('properties', sa.Column('pin_status', sa.String(length=16), server_default='', nullable=False))
    op.add_column('properties', sa.Column('provider_refs', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('properties', sa.Column('location_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'location_version')
    op.drop_column('properties', 'provider_refs')
    op.drop_column('properties', 'pin_status')
    op.drop_column('properties', 'geocode_status')
    op.drop_column('properties', 'public_location_decimals')
    op.drop_column('properties', 'location_precision')
    op.drop_column('properties', 'longitude_private')
    op.drop_column('properties', 'latitude_private')
    op.drop_column('properties', 'floor')
    op.drop_column('properties', 'building_name')
    op.drop_column('properties', 'property_kind')
    op.drop_column('properties', 'canonical_formatted_address')
    op.drop_column('properties', 'country_code')
    op.drop_column('properties', 'postal_code')
    op.drop_column('properties', 'administrative_area')
    op.drop_column('properties', 'locality')
    op.drop_column('properties', 'subpremise')
    op.drop_column('properties', 'address_line_2')
    op.drop_column('properties', 'address_line_1')
    op.drop_index(op.f('ix_property_location_evidence_verification_id'), table_name='property_location_evidence')
    op.drop_index(op.f('ix_property_location_evidence_sha256'), table_name='property_location_evidence')
    op.drop_table('property_location_evidence')
    op.drop_index(op.f('ix_property_location_verifications_state'), table_name='property_location_verifications')
    op.drop_index(op.f('ix_property_location_verifications_property_id'), table_name='property_location_verifications')
    op.drop_index(op.f('ix_property_location_verifications_address_fingerprint'), table_name='property_location_verifications')
    op.drop_table('property_location_verifications')
    op.drop_index(op.f('ix_property_regulatory_packs_country_code'), table_name='property_regulatory_packs')
    op.drop_table('property_regulatory_packs')
    # ### end Alembic commands ###
