"""property evidence ocr analysis

Revision ID: ba4bff0dd48a
Revises: 833ffed87973
Create Date: 2026-10-05 16:04:50.388251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4bff0dd48a'
down_revision: Union[str, None] = '833ffed87973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_location_evidence', sa.Column('text_source', sa.String(length=12), server_default='NONE', nullable=False))
    op.add_column('property_location_evidence', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('property_location_evidence', sa.Column('quality', sa.String(length=20), server_default='UNREADABLE', nullable=False))
    op.add_column('property_location_evidence', sa.Column('postal_matched', sa.Boolean(), nullable=True))
    op.add_column('property_location_evidence', sa.Column('owner_name_matched', sa.Boolean(), nullable=True))
    op.add_column('property_location_evidence', sa.Column('document_type_matched', sa.Boolean(), nullable=True))
    op.add_column('property_location_evidence', sa.Column('document_year', sa.Integer(), nullable=True))
    op.add_column('property_location_evidence', sa.Column('reference_number', sa.String(length=40), server_default='', nullable=False))
    op.add_column('property_location_evidence', sa.Column('signals', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_location_evidence', 'signals')
    op.drop_column('property_location_evidence', 'reference_number')
    op.drop_column('property_location_evidence', 'document_year')
    op.drop_column('property_location_evidence', 'document_type_matched')
    op.drop_column('property_location_evidence', 'owner_name_matched')
    op.drop_column('property_location_evidence', 'postal_matched')
    op.drop_column('property_location_evidence', 'quality')
    op.drop_column('property_location_evidence', 'ocr_confidence')
    op.drop_column('property_location_evidence', 'text_source')
    # ### end Alembic commands ###
