"""ZR-IDENTITY-001 Section 9.2: when raw identity evidence was deleted

Revision ID: d0bb71e525c8
Revises: 0341b3322b25
Create Date: 2026-10-01 16:29:12.460489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bb71e525c8'
down_revision: Union[str, None] = '0341b3322b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_verifications', sa.Column('evidence_purged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_verifications', 'evidence_purged_at')
    # ### end Alembic commands ###
