"""ZR-IDV-ADR-001: Veriff hosted sessions, durable webhook ledger, attempt limits

Revision ID: d3e7d3fbfb7a
Revises: d0bb71e525c8
Create Date: 2026-10-01 17:06:11.085556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e7d3fbfb7a'
down_revision: Union[str, None] = 'd0bb71e525c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_provider_events', sa.Column('payload_encrypted', sa.Text(), nullable=True))
    op.add_column('identity_provider_events', sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'processed'")))
    op.add_column('identity_provider_events', sa.Column('processing_error', sa.String(length=300), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_provider_events', sa.Column('attempts', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
    op.add_column('identity_provider_events', sa.Column('duplicate_count', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
    op.add_column('identity_regulatory_packs', sa.Column('max_attempts_per_day', sa.Integer(), nullable=False, server_default=sa.text("'5'")))
    op.add_column('identity_verifications', sa.Column('provider_session_url_encrypted', sa.String(length=2048), nullable=True))
    op.add_column('identity_verifications', sa.Column('provider_attempt_id', sa.String(length=200), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('provider_decision', sa.String(length=40), nullable=False, server_default=sa.text("''")))
    op.add_column('identity_verifications', sa.Column('consent_notice_version', sa.String(length=40), nullable=False, server_default=sa.text("''")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_verifications', 'consent_notice_version')
    op.drop_column('identity_verifications', 'provider_decision')
    op.drop_column('identity_verifications', 'provider_attempt_id')
    op.drop_column('identity_verifications', 'provider_session_url_encrypted')
    op.drop_column('identity_regulatory_packs', 'max_attempts_per_day')
    op.drop_column('identity_provider_events', 'duplicate_count')
    op.drop_column('identity_provider_events', 'attempts')
    op.drop_column('identity_provider_events', 'processing_error')
    op.drop_column('identity_provider_events', 'status')
    op.drop_column('identity_provider_events', 'payload_encrypted')
    # ### end Alembic commands ###
