"""authority verification zr-authority-002

Revision ID: ea318f7cf1bc
Revises: 8c720df07c87
Create Date: 2026-10-05 12:19:48.236740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea318f7cf1bc'
down_revision: Union[str, None] = '8c720df07c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_regulatory_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('terminology', sa.JSON(), nullable=False),
    sa.Column('sublet_consent_required', sa.Boolean(), nullable=False),
    sa.Column('co_owner_consent_required', sa.Boolean(), nullable=False),
    sa.Column('parallel_identity_intake', sa.Boolean(), nullable=False),
    sa.Column('default_validity_days', sa.Integer(), nullable=False),
    sa.Column('expiring_soon_days', sa.Integer(), nullable=False),
    sa.Column('evidence_retention_days', sa.Integer(), nullable=True),
    sa.Column('listing_control', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_regulatory_packs_country_code'), 'authority_regulatory_packs', ['country_code'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_party_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('representative_role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_by_party_id'), 'organizations', ['created_by_party_id'], unique=False)
    op.create_table('authority_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_scope_ids', sa.JSON(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('account_user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('acting_capacity', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('pack_version', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('assurance_level', sa.String(length=5), nullable=False),
    sa.Column('principal_name_encrypted', sa.Text(), nullable=True),
    sa.Column('principal_name_hash', sa.String(length=64), nullable=False),
    sa.Column('principal_party_id', sa.Integer(), nullable=True),
    sa.Column('scope_codes', sa.JSON(), nullable=False),
    sa.Column('restrictions', sa.String(length=1000), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason_code', sa.String(length=40), nullable=False),
    sa.Column('match_results', sa.JSON(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('review_reason_codes', sa.JSON(), nullable=False),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiring_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_admin_id', sa.Integer(), nullable=True),
    sa.Column('first_approver_admin_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.String(length=1000), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('is_reconsideration', sa.Boolean(), nullable=False),
    sa.Column('reconsideration_note', sa.String(length=1000), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('submit_idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_approver_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_id'], ['authority_verifications.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'idempotency_key', name='uq_authority_party_idempotency')
    )
    op.create_index(op.f('ix_authority_verifications_party_id'), 'authority_verifications', ['party_id'], unique=False)
    op.create_index(op.f('ix_authority_verifications_property_id'), 'authority_verifications', ['property_id'], unique=False)
    op.create_index(op.f('ix_authority_verifications_state'), 'authority_verifications', ['state'], unique=False)
    op.create_table('authority_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('requirement_id', sa.String(length=60), nullable=False),
    sa.Column('recipient_email_encrypted', sa.Text(), nullable=False),
    sa.Column('recipient_email_hash', sa.String(length=64), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responder_name', sa.String(length=200), nullable=False),
    sa.Column('responder_ip_hash', sa.String(length=64), nullable=False),
    sa.Column('responder_agent', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['authority_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_confirmations_recipient_email_hash'), 'authority_confirmations', ['recipient_email_hash'], unique=False)
    op.create_index(op.f('ix_authority_confirmations_token_hash'), 'authority_confirmations', ['token_hash'], unique=False)
    op.create_index(op.f('ix_authority_confirmations_verification_id'), 'authority_confirmations', ['verification_id'], unique=False)
    op.create_table('authority_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.String(length=60), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('document_reference', sa.String(length=200), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stored_filename', sa.String(length=300), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('readable', sa.Boolean(), nullable=False),
    sa.Column('property_matched', sa.Boolean(), nullable=True),
    sa.Column('name_matched', sa.Boolean(), nullable=True),
    sa.Column('principal_matched', sa.Boolean(), nullable=True),
    sa.Column('reused_elsewhere', sa.Boolean(), nullable=False),
    sa.Column('tamper_signal', sa.Boolean(), nullable=False),
    sa.Column('confirmation_id', sa.Integer(), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['authority_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_evidence_file_hash'), 'authority_evidence', ['file_hash'], unique=False)
    op.create_index(op.f('ix_authority_evidence_verification_id'), 'authority_evidence', ['verification_id'], unique=False)
    # ### end Alembic commands ###

    # ZR-AUTHORITY-002 Section 16: authority is never inferred from property
    # ownership of the account. Host self-declared records were verified
    # automatically with no evidence review, so they no longer satisfy the
    # gate -- those hosts re-verify through the new flow. Records a reviewer
    # actually verified are kept.
    op.execute(
        "UPDATE authority_records SET status = 'revoked' "
        "WHERE status = 'verified' AND CAST(id AS VARCHAR) IN ("
        "  SELECT resource_id FROM audit_events "
        "  WHERE action = 'authority_record.declare' AND resource_type = 'authority_record')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authority_evidence_verification_id'), table_name='authority_evidence')
    op.drop_index(op.f('ix_authority_evidence_file_hash'), table_name='authority_evidence')
    op.drop_table('authority_evidence')
    op.drop_index(op.f('ix_authority_confirmations_verification_id'), table_name='authority_confirmations')
    op.drop_index(op.f('ix_authority_confirmations_token_hash'), table_name='authority_confirmations')
    op.drop_index(op.f('ix_authority_confirmations_recipient_email_hash'), table_name='authority_confirmations')
    op.drop_table('authority_confirmations')
    op.drop_index(op.f('ix_authority_verifications_state'), table_name='authority_verifications')
    op.drop_index(op.f('ix_authority_verifications_property_id'), table_name='authority_verifications')
    op.drop_index(op.f('ix_authority_verifications_party_id'), table_name='authority_verifications')
    op.drop_table('authority_verifications')
    op.drop_index(op.f('ix_organizations_created_by_party_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_authority_regulatory_packs_country_code'), table_name='authority_regulatory_packs')
    op.drop_table('authority_regulatory_packs')
    # ### end Alembic commands ###
